# Generated by Django 5.2.2 on 2025-09-25 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('population', models.BigIntegerField()),
                ('continent', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital_name', models.CharField(max_length=100)),
                ('area_sq_km', models.IntegerField()),
                ('population', models.BigIntegerField()),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capital', to='app.country')),
            ],
        ),
    ]
